package com.bestcfm.util;

import lombok.Getter;

public enum ErrorCodeEnum {
	// 公共的错误信息
	COMMON_NOT_SUPPORT_REQUEST_SOURCE("不支持的请求来源", 1000),
	COMMON_NEED_SUPPLIERID("供应商信息必填", 1001),
	COMMON_ADD_UPDATE_NEED_TCMANAGERID("保存时同程经理标识必填", 1002),
	COMMON_HAS_NO_PRIVILEGE("没有相应的权限", 1003),
	COMMON_AUDIT_STATUS_ERROR("审核时必须是审核通过或者不通过状态", 1004),
	COMMON_REJECT_MUST_HAVE_REASON("审核不通过时必须填写原因", 1005),
	COMMON_AUDIT_MUST_PENDINGAUDIT("资源审核时状态必须是待审核", 1006),
	
	COMMON_NEED_TCMANAGERID("同程经理标识必填", 1007),
	// 景点资源报错信息
	SCENIC_NOT_FOUND_SCENIC_RESOURCE("未找到指定的景点资源", 2000),
	//酒店资源报错信息
	HOTEL_NOT_FOUND_HOTEL_RESSOURECE("未找到国内酒店资源",3000),
	INTER_HOTEL_NOT_FIND_HOTEL_RESOURCE("未找到指定的国际酒店资源", 8000),
	INTER_HOTEL_NOT_SUPPORT_ADD("id大于0不支持新增服务,请使用编辑服务", 8001),
	INTER_HOTEL_FAILED_ADD_RESOURCE("添加国际酒店主信息失败", 8002),
	INTER_HOTEL_FAILED_ADD_RESOURCE_EXT("添加国际酒店扩展信息失败", 8003),
	INTER_HOTEL_NOT_SUPPORT_UPDATE("ID为空或者无效值，不支持编辑服务", 8004),
	INTER_HOTEL_FAILED_UPDATE_RESOURCE("更新国际酒店信息失败", 8005),
	INTER_HOTEL_FAILED_UPDATE_RESOURCE_EXT("更新国际酒店扩展信息失败", 8006),
	INTER_HOTEL_INVALID_PARAMETER("请求参数无效", 8007),
	INTER_HOTEL_AUDIT_STATUS_ERROR("国际酒店资源不是待提交或者待审核状态", 8008),
	INTER_HOTEL_COMMIT_AUDIT_ERROR("该状态的国际酒店资源不可以提交审核", 8009),
	INTER_HOTEL_CANCEL_AUDIT_ERROR("只有待审核的资源可以撤销审核", 8010),
	INTER_HOTEL_FAILED_COMMIT_CANCEL("提交审核或者撤销审核失败", 8011),
	INTER_HOTEL_FAILED_DELETE("国际酒店资源删除失败", 8012),
	INTER_HOTEL_STATUS_DELETE_ERROR("只支持未走过审核流程的国际酒店删除", 8013),
	INTER_HOTEL_NOT_FIND_DETAIL("未找到指定的国际酒店详情", 8014),
	INTER_HOTEL_FAILED_AUDIT_PASS("审核通过复制数据到主库失败", 8015),
	INTER_HOTEL_NOT_FIND_HOTEL_RESOURCE_EXT("未找到国际酒店资源扩展信息", 8016),
	INTER_HOTEL_FAILED_UPDATE_AUDIT("更新审核状态失败", 8017),
	INTER_HOTEL_FAILED_UPDATE_STATUS("该状态的国际酒店资源不能编辑", 8018),
	INTER_HOTEL_ADD_MUST_CREATERID("新增国际酒店必须有创建人标识",8019),
	INTER_HOTEL_ADD_MUST_CREATERNAME("新增国际酒店必须传创建人名字", 8020),
	INTER_HOTEL_UPDATE_MUST_UPDATERID("编辑国际酒店必须传更新人标识",8021),
	INTER_HOTEL_UPDATE_MUST_UPDATERNAME("编辑国际酒店必须传更新人名字",8022),
	INTER_HOTEL_DATA_INVALID("无效状态的数据不能进行操作", 8023),
	INTER_HOTEL_ADD_MUST_FACILITIES("国际酒店设施不能为空", 8024),
	INTER_HOTEL_FAILED_ADD_FACILITIES("添加国际酒店设施失败", 8025),
	INTER_HOTEL_FAILED_UPDATE_FACILITIES("更新国际酒店设施失败", 8026),
	INTER_HOTEL_FAILED_ADD_IMAGES("添加国际酒店图片失败", 8027),
	INTER_HOTEL_FAILED_UPDATE_IMAGES("更新国际酒店图片失败", 8028),
	INTER_HOTEL_AUDIT_COPY_FACILITY_ERROR("审核时复制酒店设施数据出错", 8029),
	INTER_HOTEL_AUDIT_COPY_IMAGES_ERROR("审核时复制图片数据时出错", 8030),
	INTER_HOTEL_COMMIT_AUDIT_STATE_ERROR("该状态的国际酒店资源无法提交或撤销审核", 8031),

	DEMOSTIC_HOTEL_STATUS_DELETE_ERROR("只支持未走过审核流程的国内酒店删除", 9004),
	DEMOSTIC_HOTEL_INVALID_PARAMETER("请求参数id不合法", 9000),
	DEMOSTIC_HOTEL_INVALID_PARAMETER2("请求参数bianHUan不合法", 9000),
	DEMOSTIC_HOTEL_FAILED_DELETE("国内酒店资源删除失败", 9001),
	DEMOSTIC_HOTEL_FAILED_COMMIT_CANCEL("提交审核或者撤销审核失败", 9002),
	DEMOSTIC_HOTEL_NOT_FIND_HOTEL_RESOURCE("未找到指定的国内酒店政策资源",9005),
	DEMOSTIC_HOTEL_NOT_FIND_ROOM_RESOURCE("未找到指定的国内酒店资源",9006),
	INTER_FLIGHT_INVALID_PARAMETER("请求参数无效", 9003),
	INTER_FLIGHT_NOT_FIND_DETAIL("未找到指定的国际机票详情", 9004),
	DEMOSTIC_HOTEL_INVALID_PARAMETERID1("请求id不能为空",9008),
	DEMOSTIC_HOTEL_INVALID_PARAMETERID2("请求id要大于0",9009),

	//国际酒店房型报错信息
	
	//国际酒店房型政策报错信息
	INTER_HOTEL_NOT_FOUND_HOTEL_ROOM_Policy("未找到指定的信息",6000),
	INTER_HOTEL_FAILED_UPDATE_TEMP_HOTEL_ROOM_Policy("更新临时库政策信息失败",6001),
	INTER_HOTEL_FAILED_UPDATE_HOTEL_ROOM_Policy("更新主库政策信息失败",6002),
	INTER_HOTEL_FAILED_ADD_TEMP_HOTEL_ROOM_Policy("新增临时库政策信息失败",6003),
	INTER_HOTEL_FAILED_ADD_HOTEL_ROOM_Policy("新增主库政策信息失败",6004),
	INTER_HOTEL_FAILED_UPDATE_LOG_HOTEL_ROOM_Policy("更新日志库政策信息失败",6005),
	INTER_HOTEL_FAILED_ADD_LOG_HOTEL_ROOM_Policy("新增日志库政策信息失败",6006),
	INTER_HOTEL_FAILED_TO_FIND_HOTEL_ROOM("主库酒店房型不存在",6007),
	INTER_HOTEL_FAILED_DELETE_HOTEL_ROOM_Policy("请求不合法",6008);
	
	
	@Getter
	private String description;
	@Getter
	private Integer code;
	
	private ErrorCodeEnum(String description,Integer code) {
		this.description=description;
		this.code=code;
	}
}
